### ISSUE TITLE
Cannot match valid URL encoded characters in a path segment

### ISSUE THREAD

**Issue by senior** [juxt/bidi#111]
I am porting over an existing application from moustache to bidi and hit an issue. I've got valid URL encoded characters that are part of the path segment that are not being parsed incorrectly. I think [this code](https://github.com/juxt/bidi/blob/master/src/bidi/bidi.cljc#L141) is causing my issue. The application I'm working on has a [shorthand query syntax](https://docs.puppetlabs.com/puppetdb/3.2/api/query/v4/resources.html#pdbqueryv4resourcestypetitle), where a user can query a resource with it's type and title in the path. With file resources, the path is the title, which leads to URLs like '/v4/nodes/foo.com/resources/File/%2Fpath%2Fto%2Ffile'.  This doesn't get matched by bidi as the % is not recognized by the regex I reference above.

I'm happy to put together a PR to make that change, but with the comment above that regex, it seems like % is intentionally not there. 

Below is a basic test case that reproduces the issue I'm having:

``` clojure
(deftest url-encoded-slashes-test
  (let [myroutes ["/" {[:foo "/" :bar] :matched}]]
    (is (= {:route-params {:foo "part1", :bar "encoded%2Fpart"}, :handler :matched}
           (match-route myroutes "/part1/encoded%2Fpart")))))
```

**Comment by malcolmsparks** [comment]
Have you read this: https://github.com/juxt/bidi#regular-expressions ?

By default, a keyword will match a limited set of characters, in an attempt
to defend against injection attacks.

Hence

[:foo "/" :bar]

means :foo and :bar are restricted to this regex pattern:
 [A-Za-z0-9\\-\\_\\.]+

If you want a different regex, you must use an inner vector pair, the first
item being the regex and the second item the keyword, like this :-

[:foo "/" [#".*" :bar]]

I hope I've understood the problem and this helps, otherwise please let me
know

**Comment by senior** [comment]
You have understood the problem. I can use the regex pattern like you have described. I saw the regex section in that doc and didn't think I needed it.

Thanks for the clarification!

**Comment by tangrammer** [comment]
👍
