### ISSUE TITLE
Struggling To Translate From Compojure

### ISSUE THREAD

**Issue by xcthulhu** [juxt/bidi#119]
Hi!

I am trying to migrate to `bidi` from `compojure`, since I would like to do server side rendering as well as SPA, and I am relatively convinced using one routing system for both Clojure and ClojureScript is the best route (sorry for the pun).

Anyway, I am really struggling with translating the following simple `compojure` route to `bidi`:

```clj
(defroutes app-routes
  (GET "/" [] (ring.util.response/redirect "/index.html"))
  (compojure.route/resources "/")
  (GET "/image/*.jpg" [] (ring.util.response/redirect "/image/unavailable.jpg")))
```

This isn't really an *issue*, I'm just a (confused) new user...

**Comment by actsasgeek** [comment]
:+1:

After looking at the documentation, I have no idea how to map something similar:
```clojure
 (compojure/defroutes app
   (compojure/GET "/" [] (file-response "index.html" {:root "resources/public"}))
   (route/resources "/")
   (route/not-found "Not Found"))
```
to `bidi`.

It's not like there's only one way to do it `compojure` but I have been completely unable to figure out how to do it in `bidi`.

**Comment by SevereOverfl0w** [comment]
Off the top of my head, it's similar to this:

```
["/" ["" (file-response "index.html" {:root "resources/public"}) ;; file-response is a ring util fn right?
       "" (->ResourcesMaybe {:prefix "public"}) ;; This won't work, there's a way though, @malcolmsparks knows
       true (yada nil)]] ;; True matches all routes, use it last as a catch-all
```

**Comment by malcolmsparks** [comment]
bidi does not serve individual files, but it does have basic support for serving directories and classpath resources.

But here's an approximate solution:

```clojure
["" 
  [
    ["/" (bidi.ring/files {:root "resources/public"})]
    ["/" (bidi.ring/resources-maybe {:prefix ""})]
    [true (fn [req] {:status 400 :body "Not found"})]]]
```

[yada](https://github.com/juxt/yada) is more adept as serving files and resources:

```clojure
["" 
  [
    ["/index.html" (yada (io/file "resources/public/index.html"))]
    ["/" (yada (new-classpath-resource ""))]
    [true (yada nil)]
  ]
]
```

**Comment by actsasgeek** [comment]
@malcolmsparks Thank you for taking the time to answer this.

1. I wonder if this might not be profitably included in the `README.md`. Others are bound to ask and because most of the `lein` templates will use `compojure`, some note on conversion seems like it may be helpful and encourage adoption of `bidi`.
2. The comparison table at the top of the `README.md` suggests that bidi is a wholesale replacement for `compojure` and this seems not to be the case or at least `bidi` cannot easily replace it. Perhaps this might suggest a missing feature for `bidi`?

As for `yada`, I've watched your presentations and love it but I cannot also convert to `aleph`.

**Comment by malcolmsparks** [comment]
I think it's still fair to say that bidi is a wholesale replacement for compojure. Both are routing libraries. Compojure does things a bit differently and has different semantics which means that some things that are easy in Compojure are harder in bidi (and vice versa - for example, Compojure does not make it easy for you to construct URIs from handlers). I think this issue is a bit of an edge case because serving files and resources is something that is arguably outside the scope of either Compojure or bidi.

**Comment by malcolmsparks** [comment]
Out of interest, what webserver are you using? I'm thinking of extending yada's coverage of webservers.

**Comment by actsasgeek** [comment]
Currently, `immutant` but I imagine `jetty` is the most popular because it is often the default.

For myself, I think being able to route to a specific file is pretty basic especially if you want to use routes as aliases ("/", "/index.html" and "/home.html" all go to the same specific resource file).

**Comment by malcolmsparks** [comment]
I think bidi could definitely support individual files like this, thanks for the idea.
