### ISSUE TITLE
Regular Expression matches not working?

### ISSUE THREAD

**Issue by grammati** [juxt/bidi#43]
Matching with a regular expression does not seem to be working, unless I am misunderstanding something.

Two cases:

```
(match-route [[#"/x+" :x] :x-match] "/xxx") => {:handler :x-match, :route-params {:x "x"}}
```
Note that only one character from the "xxx" ended up in route-params.

```
(match-route [[#"/x+" :x] :x-match] "/x") => nil
```
This should match the single "x" in the path.

**Comment by malcolmsparks** [comment]
I'm sorry that you're having problems. 

Let's me try to explain.

```clojure
[#"/x+" :x]
```

means you want to match some string of x's, and then capture a non-empty string, returned as :x. Because #"/x+" is greedy, it takes as many x's as it can, then leaves the remaining "x" as the binding to :x. You could use a reluctant quantifier, see here: http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html

But I don't think that's your intention. I think you actually mean this :- 

```clojure
(bidi/match-route [[[#"/x+" :x]] :x-match] "/xxxx")
```

Normally I pattern can be specified as a vector when you want to capture values.

```clojure
["/" :a "/docs/" :docid "/version/" :v "/" :x "/" :y]
```

By default, keywords assume a conservative regex of ```#"[A-Za-z0-9\\-\\_\\.]+"```

But I think you're saying that for :x, you want to provide your own regex.

So in the above example, :x can be replaced by a vector pair.

```clojure
["/" :a "/docs/" :docid "/version/" :v "/" [#"/x+" :x] "/" :y]
```

I hope this helps.

**Comment by grammati** [comment]
Thank you for the explanation, Malcolm.

I'm still confused about a few things, but is there a better forum to ask questions like this, rather than a github issue?

**Comment by malcolmsparks** [comment]
Hi - I think it's good as a github issue - there's a record of the
conversation that will be searchable and may help others. Please go ahead
and raise more issues if you're confused by anything else.
